# Image
version: "3.9"
services:
  server:
    image: andrewt51/server
    # build:
    #   context: ./server
    #   dockerfile: Dockerfile 
  client:
    image: andrewt51/client
    # build:
    #   context: ./client
    #   dockerfile: Dockerfile 
  reverse-proxy:
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    environment:
      - SERVER_NAME=triggatron.co.uk
      - CLIENT_PORT=80
    restart: always
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./data/nginx:/etc/nginx/conf.d
  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
